name: 'Clang Tools'
on:
  - pull_request

jobs:
  scan-build:
    name: "Clang Static Analyzer"
    runs-on: ubuntu-20.04

    steps:
      - name: Install Clang Tools
        run: |
          sudo apt-get install clang-tools-9

          echo "/usr/lib/llvm-9/bin" >> $GITHUB_PATH

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Scan-Build
        run: |
          mkdir -p scan-build-out

          # scan-build clang, but turn off clang warnings
          scan-build -analyze-headers -k --status-bugs \
            -o scan-build-out \
            clang -w -c test.c -o /dev/null

      - name: Upload Scan-Build Results
        uses: actions/upload-artifact@v1
        with:
          name: "Scan-Build HTML Output"
          path: scan-build-out
        if: ${{ always() }}

  clang-tidy:
    name: "Clang Tidy"
    runs-on: ubuntu-20.04

    steps:
      - name: Install Clang Tidy
        run: |
          sudo apt-get install clang-tidy-9

          echo "/usr/lib/llvm-9/bin" >> $GITHUB_PATH

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Clang-Tidy
        run: |
          clang-tidy --warnings-as-errors='*' \
            test.c --
